# Generated by Django 6.0 on 2025-12-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='inspecoes/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inspecoes.inspecao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
