# Generated by Django 6.0 on 2025-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('avaliador', 'Avaliador'), ('gerente', 'Gerente'), ('engenheiro', 'Engenheiro'), ('fiscal', 'Fiscal/QA'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20),
        ),
    ]
