# Generated by Django 6.0 on 2025-12-16 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    Profile = apps.get_model("accounts", "UserProfile")
    mapping = {
        "admin": "admin",
        "avaliador": "nivel2",
        "gerente": "nivel2",
        "engenheiro": "nivel2",
        "fiscal": "nivel2",
        "visualizador": "nivel1",
    }
    for old_value, new_value in mapping.items():
        Profile.objects.filter(role=old_value).update(role=new_value)
    Profile.objects.exclude(role__in=mapping.values()).update(role="nivel1")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
        ('obras', '0004_obra_capa_alter_obra_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('nivel2', 'Nível 2'), ('nivel1', 'Nível 1')], default='nivel1', max_length=20),
        ),
        migrations.CreateModel(
            name='ObraAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alocado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='obras.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_alocadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alocação de obra',
                'verbose_name_plural': 'Alocações de obras',
                'ordering': ('obra__nome', 'usuario__username'),
                'unique_together': {('obra', 'usuario')},
            },
        ),
    ]
