"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load a local .env file (optional) so os.getenv() works in development.
_env_path = BASE_DIR / ".env"
if _env_path.exists():
    try:
        env_text = _env_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        env_text = _env_path.read_text(encoding="utf-8", errors="ignore")

    for raw_line in env_text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        os.environ.setdefault(key, value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-insecure-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    _raw_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
    ALLOWED_HOSTS = [h.strip() for h in _raw_allowed_hosts.split(",") if h.strip()]

if not DEBUG and SECRET_KEY == "dev-insecure-key":
    raise ValueError("Set DJANGO_SECRET_KEY for production (DJANGO_DEBUG=False).")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de negocio
    'accounts',
    'obras',
    'inspecoes',

    # 3rd party
    'crispy_forms',
    'crispy_bootstrap5',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _parse_database_url(database_url: str) -> dict:
    parsed = urlparse(database_url)

    if parsed.scheme in {"postgres", "postgresql"}:
        query = parse_qs(parsed.query)
        sslmode = (query.get("sslmode") or [None])[0]
        conn_max_age = int(os.getenv("DB_CONN_MAX_AGE", "60"))

        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or 5432),
            "CONN_MAX_AGE": conn_max_age,
        }
        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}
        return config

    if parsed.scheme == "sqlite":
        # sqlite:///relative/path.db or sqlite:////absolute/path.db
        sqlite_path = unquote(parsed.path or "")
        if sqlite_path.startswith("/") and len(sqlite_path) >= 3 and sqlite_path[2] == ":":
            sqlite_path = sqlite_path.lstrip("/")
        return {"ENGINE": "django.db.backends.sqlite3", "NAME": sqlite_path}

    raise ValueError(f"Unsupported DATABASE_URL scheme: {parsed.scheme!r}")


DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()
DB_ENGINE = (os.getenv("DB_ENGINE") or "").strip().lower()

if DATABASE_URL:
    DATABASES = {"default": _parse_database_url(DATABASE_URL)}
elif DB_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME") or os.getenv("POSTGRES_DB") or "simob",
            "USER": os.getenv("DB_USER") or os.getenv("POSTGRES_USER") or "postgres",
            "PASSWORD": os.getenv("DB_PASSWORD") or os.getenv("POSTGRES_PASSWORD") or "",
            "HOST": os.getenv("DB_HOST") or os.getenv("POSTGRES_HOST") or "127.0.0.1",
            "PORT": os.getenv("DB_PORT") or os.getenv("POSTGRES_PORT") or "5432",
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": (
                {"sslmode": os.getenv("DB_SSLMODE")}
                if os.getenv("DB_SSLMODE")
                else {}
            ),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary (uploads/visualização de mídia)
# Ative definindo CLOUDINARY_ENABLED=true (ou apenas setando as credenciais).
_cloudinary_cloud_name = (os.getenv("CLOUDINARY_CLOUD_NAME") or "").strip()
_cloudinary_api_key = (os.getenv("CLOUDINARY_API_KEY") or "").strip()
_cloudinary_api_secret = (os.getenv("CLOUDINARY_API_SECRET") or "").strip()

_cloudinary_configured = all(
    [_cloudinary_cloud_name, _cloudinary_api_key, _cloudinary_api_secret]
)

_cloudinary_enabled_raw = os.getenv("CLOUDINARY_ENABLED")
if _cloudinary_enabled_raw is None:
    CLOUDINARY_ENABLED = _cloudinary_configured
else:
    CLOUDINARY_ENABLED = _cloudinary_enabled_raw.strip().lower() in {"1", "true", "yes", "on"}

if CLOUDINARY_ENABLED:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": _cloudinary_cloud_name,
        "API_KEY": _cloudinary_api_key,
        "API_SECRET": _cloudinary_api_secret,
    }

    # Django 4.2+ usa STORAGES; DEFAULT_FILE_STORAGE ainda funciona mas é legado.
    try:
        import django  # type: ignore

        if getattr(django, "VERSION", (0, 0)) >= (4, 2):
            STORAGES = {
                "default": {
                    "BACKEND": "app.storage_backends.CloudinaryMediaStorage",
                },
                "staticfiles": {
                    "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
                },
            }
        else:
            DEFAULT_FILE_STORAGE = "app.storage_backends.CloudinaryMediaStorage"
    except Exception:
        DEFAULT_FILE_STORAGE = "app.storage_backends.CloudinaryMediaStorage"

LOGOUT_REDIRECT_URL = "login"
LOGIN_URL = "login"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Production security (Render/proxies)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

    SECURE_SSL_REDIRECT = (
        os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").strip().lower()
        in {"1", "true", "yes", "on"}
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "False").strip().lower()
        in {"1", "true", "yes", "on"}
    )
    SECURE_HSTS_PRELOAD = (
        os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "False").strip().lower()
        in {"1", "true", "yes", "on"}
    )

    _csrf_trusted = []
    _render_external_url = (os.getenv("RENDER_EXTERNAL_URL") or "").strip().rstrip("/")
    if _render_external_url:
        _csrf_trusted.append(_render_external_url)

    _csrf_trusted_raw = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
    for origin in _csrf_trusted_raw.split(","):
        origin = origin.strip().rstrip("/")
        if origin:
            _csrf_trusted.append(origin)

    if _csrf_trusted:
        CSRF_TRUSTED_ORIGINS = sorted(set(_csrf_trusted))
