# Generated by Django 6.0 on 2025-12-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_tarefa_percentual_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='custo_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('arquivada', 'Arquivada')], default='ativa', max_length=20),
        ),
        migrations.AddField(
            model_name='pendencia',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnexoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='obras.categoria')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='obras.obra')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
    ]
