# Generated by Django 6.0 on 2025-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_custo_previsto_obra_custo_real_obra_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='obras/capas/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20),
        ),
    ]
