# Generated by Django 6.0 on 2025-12-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_obra_capa_alter_obra_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='custo_previsto',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='custo_real',
        ),
    ]
