# Generated by Django 6.0 on 2025-12-16 16:25

import django.core.validators
import obras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_remove_obra_custo_previsto_remove_obra_custo_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencia',
            name='imagem_problema',
            field=models.ImageField(blank=True, null=True, upload_to='pendencias/problemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), obras.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='pendencia',
            name='imagem_resolucao',
            field=models.ImageField(blank=True, null=True, upload_to='pendencias/resolucoes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), obras.models.validate_image_file]),
        ),
    ]
